#ifndef CUBEMAPTEXTUREFACE_H
#define CUBEMAPTEXTUREFACE_H
#include "../../GL/glad.h"

namespace GL
{
    enum class CubemapTextureFace
    {
        CUBE_MAP_POS_X = GL_TEXTURE_CUBE_MAP_POSITIVE_X,
        CUBE_MAP_NEG_X = GL_TEXTURE_CUBE_MAP_NEGATIVE_X,
        CUBE_MAP_POS_Y = GL_TEXTURE_CUBE_MAP_POSITIVE_Y,
        CUBE_MAP_NEG_Y = GL_TEXTURE_CUBE_MAP_NEGATIVE_Y,
        CUBE_MAP_POS_Z = GL_TEXTURE_CUBE_MAP_POSITIVE_Z,
        CUBE_MAP_NEG_Z = GL_TEXTURE_CUBE_MAP_NEGATIVE_Z
    };
} // GL

#endif //CUBEMAPTEXTUREFACE_H
