#ifndef TEXTUREPARAMNAME_H
#define TEXTUREPARAMNAME_H
#include <cstdint>

#include "../../GL/glad.h"

namespace GL
{
    enum class FilterMode
    {
        NEAREST = GL_NEAREST,
        LINEAR = GL_LINEAR,
        NEAREST_MIPMAP_NEAREST = GL_NEAREST_MIPMAP_NEAREST,
        LINEAR_MIPMAP_NEAREST = GL_LINEAR_MIPMAP_NEAREST,
        NEAREST_MIPMAP_LINEAR = GL_NEAREST_MIPMAP_LINEAR,
        LINEAR_MIPMAP_LINEAR = GL_LINEAR_MIPMAP_LINEAR
    };
} // GL

#endif //TEXTUREPARAMNAME_H
